name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions: write-all
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
  
        - name: Upload files to S3 with AWS CLI
          run: |
            aws s3 sync ./dist/ s3://bayuwrdani/train/${GITHUB_SHA} --delete --acl public-read
         
        - name: Get changed files
          id: changed_files
          uses: ./.github/actions/get-changed-files
        - name: Create Comment
          if: ${{ steps.get-changed-files.outputs.files }}
          run: |
            # Using GitHub API to create a comment on the PR
            PR_NUMBER=${{ github.event.pull_request.number }}
            COMMENT="Untuk melakukan testing data pr ini bisa menggunakan link berikut https://spa.bayuwardani.my.id/dev.html?appName=@oci/travel-train&appUrl=https://bayuwrdani.s3.ap-southeast-2.amazonaws.com/train/${GITHUB_SHA}/oci-travel-train.js"
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
            curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"`

