name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - shell: bash
          env:
            SUPER_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
          run: |
            echo "$SUPER_SECRET"
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: upload to s3
          uses: shallwefootball/upload-s3-action@v1.3.3
          with:
            # aws key id
            aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            # aws secret access key
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
            # aws bucket name
            aws_bucket: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            # directory to upload
            source_dir: ./dist
            # destination directory for upload
            destination_dir: spa
