name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - shell: bash
          env:
            S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          run: |
            echo "$S3_ACCESS_KEY_ID"
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: Upload S3    
          uses: shallwefootball/s3-upload-action@master
          id: S3
          with:
            aws_key_id: ${{secrets.S3_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.S3_SECRET_ACCESS_KEY}}
            aws_bucket: bayuwrdani
            source_dir: ./dist
        - name: Link To Report
          run: echo 
        
