name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: upload to s3
          uses: Noelware/s3-action@2
          with:
              directories: ./dist
              access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              path-format: '/$(tag)'
              secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
              endpoint:  ${{secrets.AWS_S3_ENDPOINT_URL}}
              prefix: /artifacts
              region: idn
              bucket: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
