name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-2
  
        - name: Upload files to S3 with AWS CLI
          run: |
            aws s3 sync ./dist/ s3://bayuwrdani/train/$(git rev-parse --short "$GITHUB_SHA") --delete 
        
