name: Run tests

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - shell: bash
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          run: |
            echo "$AWS_ACCESS_KEY_ID"
        - name: build
          uses: actions/setup-node@v4.0.2
        - run: npm ci
        - run: npm run build --if-present
        - name: Upload file to bucket
          uses: koraykoska/s3-upload-github-action@master
          env:
            FILE: ./dist/
            S3_ENDPOINT: 'nos.wjv-1.neo.id'
            S3_BUCKET: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
            S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
